sql script

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -109,6 +109,13 @@ jobs:
       - name: Run Postman tests
         run: newman run ./tests/authentification.json -e ./tests/postman_environment.json
 
+      - name: Run Newman Tests2
+        run: |
+              newman newman run ./tests/authentification.json -e ./tests/postman_environment.json > newman.log 2>&1 # Capturing Newman log output to a file
+              exitCode=$?
+              cat newman.log # Displaying Newman log output in the workflow execution log
+              exit $exitCode # Exiting with Newman's exit code to propagate test failures
+
       - name: Show App Log2
         run: cat app.log # Displaying log output in the workflow execution log
 
